// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2Jd8ojs3QEXZKG1YO3-aytSOwMhq6FI',
    appId: '1:1096088644564:web:6e1ad425356acf65f90441',
    messagingSenderId: '1096088644564',
    projectId: 'social-de001',
    authDomain: 'social-de001.firebaseapp.com',
    storageBucket: 'social-de001.appspot.com',
    measurementId: 'G-L21T5H4YWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcx1HrrIfOtTW6qwH1kCZ7Gtc7AuXTTS0',
    appId: '1:1096088644564:android:2337a42ff712f30cf90441',
    messagingSenderId: '1096088644564',
    projectId: 'social-de001',
    storageBucket: 'social-de001.appspot.com',
  );
}
